"use client";

import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Sidebar from "@/app/components/Sidebar";
import { Toaster } from "sonner";

// Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Metadata
// export const metadata = {
//   title: "Task Board App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  /**
   * ✔ Check: If the current path starts with "/dashboard/admindashboard"
   * Then show admin UI (Navbar + Sidebar)
   */
  const showAdminLayout = pathname.startsWith("/dashboard/admindashboard");

  return (
    <html lang="en">
      <head>
        {/* Keep dark mode state */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>

      <body className="bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100">
        <Toaster richColors position="top-right" />

        {/* 
          ✔ Admin UI ONLY inside dashboard pages
        */}
        {showAdminLayout && <Navbar />}
        {showAdminLayout && <Sidebar />}

        <main
          className={
            showAdminLayout
              ? "pt-16 pl-[250px] p-6 transition-all duration-300"
              : "p-0"
          }
        >
          {children}
        </main>
      </body>
    </html>
  );
}
